# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- script: npm install
  displayName: npm install

- script: node build-script.js
  displayName: node build-script.js

- powershell: Start-Process npx -ArgumentList 'serve', '-l 5858'
  displayName: Start website on localhost

- task: accessibility-insights@1
  inputs:
    url: 'http://localhost:5858'
    repoServiceConnectionName: 'repo-connection'

- publish: '$(System.DefaultWorkingDirectory)/_accessibility-reports'
  displayName: Upload report artifact
  condition: always()
  artifact: 'accessibility-reports'